---
- name: install docker
  hosts: web
  tasks:
    - name: remove repository
      yum_repository:
        name: dockerrepo
        state: absent

    - name: yum-clean-metadata
      command: yum clean metadata

    - name: install base packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - yum-utils
        - tree

    - name: add repo
      get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker.repo
        owner: root
        group: root
        mode: '0644'

    - name: install docker packages
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: start docker service
      service:
        name: docker
        enabled: true
        state: started
...
